version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-2:368772107083:task-definition/My-TaskDef:1"
        LoadBalancerInfo:
          ContainerName: "nestjs"
          ContainerPort: 3000
