Version: 0.2
env:
  variables:
    ECR_URI: "368772107083.dkr.ecr.us-east-2.amazonaws.com/officetest"
    REPOSITORY_URI: "https://github.com/Vardaan-16/Officetest"
    
  secrets-manager:
    DOCKERHUB_USERNAME: "arn:aws:secretsmanager:us-east-2:368772107083:secret:docker/Account/credentials-1NLbNK:username"
    DOCKERHUB_PASSWORD: "arn:aws:secretsmanager:us-east-2:368772107083:secret:docker/Account/credentials-1NLbNK:password"

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin $ECR_URI
  build:
    commands:
      - echo build started on 'date'
      - echo building the Docker image..
      - docker build -t $ECR_URI:nestjs .
      - docker tag $ECR_URI:nestjs $ECR_URI:$IMAGE_TAG
  post_build:
    commands:  
      - echo build complete 'date'
      - echo pushing the docker image
      - docker push $ECR_URI:$IMAGE_TAG
      - echo Writing imageDetail file...
      - printf '[{"name":"nestjs","imageUri":"368772107083.dkr.ecr.us-east-2.amazonaws.com/officetest:latest"}]' > imagedefinitions.json 
  artifacts:
    files: 
      - imagedefinitions.json
