Version: 0.2
env:
  variables:
    ECR_URI: "https://us-east-2.console.aws.amazon.com/ecr/repositories/private/368772107083/officetest?region=us-east-2"
    REPOSITORY_URI: "https://github.com/Vardaan-16/Officetest"
    
  secrets-manager:
    DOCKERHUB_USERNAME: "arn:aws:secretsmanager:us-east-2:368772107083:secret:docker/Account/credentials-1NLbNK:username"
    DOCKERHUB_PASSWORD: "arn:aws:secretsmanager:us-east-2:368772107083:secret:docker/Account/credentials-1NLbNK:password"

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin $ECR_URI
  build:
    commands:
      - echo build started on 'date'
      - echo building the Docker image..
      - docker build -t nextjs:1
      - docker tag nextjs:1 368772107083.dkr.ecr.us-east-2.amazonaws.com/officetest
  post_build:
    commands:  
      - echo build complete 'date'
      - echo pushing the docker image
      - docker push 368772107083.dkr.ecr.us-east-2.amazonaws.com/officetest
